swagger: '2.0'
info:
  title: User API
  description: API for managing users
  version: 1.0.0

host: YOUR_GATEWAY_HOSTNAME  # Filled in by API Gateway
schemes:
  - https
basePath: /

x-google-backend:
  address: https://springboot-firestore-app-589874948858.us-central1.run.app

paths:
  /users:
    get:
      summary: Get all users
      operationId: getAllUsers
      produces:
        - application/json
      responses:
        '200':
          description: A list of users
          schema:
            type: array
            items:
              $ref: '#/definitions/User'

    post:
      summary: Create a new user
      operationId: createUser
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: user
          required: true
          schema:
            $ref: '#/definitions/User'
      responses:
        '200':
          description: The created user
          schema:
            $ref: '#/definitions/User'

  /users/{id}:
    delete:
      summary: Delete a user by ID
      operationId: deleteUser
      parameters:
        - name: id
          in: path
          required: true
          type: string
      responses:
        '200':
          description: User deleted

definitions:
  User:
    type: object
    properties:
      id:
        type: string
      name:
        type: string
      age:
        type: integer
